export { default as MainContent } from './mainContent/mainContent'
export { default as Signup} from './signup/signup'
export { default as Signin} from './signin/signin'
export { default as ArticleOpen } from './articleOpen/articleOpen'
export { default as NewArticle } from './newArticle/newArticle'
export { default as ProfilePage } from './profile/profile'